import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import vase from "../../public/vase.png";
import purple_orchid from "../../public/purple_orchid.png";

const picArray = [
  {
    src: vase,
    alt: "Vase Image",
    link: "/acrylics",
  },
  {
    src: purple_orchid,
    alt: "Purple Orchid Image",
    link: "/watercolors",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Hannah Daudelin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.page}>
        <h1>Hannah Daudelin</h1>
        <div className={styles.navigation}>
          <a href="/about">About</a>
          <a href="/portfolio">Portfolio</a>
        </div>
        <div className={styles.gallery}>
          {picArray.map((pic) => (
            <a href={pic.link}>
              <Image
                className={styles.picture}
                src={pic.src}
                alt={pic.alt}
                width={200}
                priority
              />
            </a>
          ))}
        </div>
      </main>
    </>
  );
}
