import Navbar from "./navbar";
import Footer from "./footer";
import styles from "@/styles/Layout.module.css";
import Head from "next/head";

interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Hannah Daudelin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Navbar />
        <main className={styles.mainContentWrapper}>{children}</main>
        <Footer />
      </div>
    </>
  );
}
